spring:
  application:
    name: client2


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5  
      
server:
  port: 8002 